### ISSUE TITLE
B站看到大佬的留言过来的

### ISSUE THREAD

**Issue by nbotu** [yzy613/ddns#2]
首先感谢作者提供这样的一个程序，闲着在家无聊想玩玩ipv6的东西，看了下教程，对小白似乎不友好，我是一点没用接触过这方面，一点不懂的。首先配置文件我是这样配置的：
![image](https://user-images.githubusercontent.com/64408436/80781167-f5eb7380-8ba3-11ea-834c-33f81122a610.png)

我也不知道是不是这样配置，然后我一个阿里云的域名解析到这个ipv6地址

![image](https://user-images.githubusercontent.com/64408436/80781209-1ddad700-8ba4-11ea-8d80-cbef968cfad5.png)
然后启动客户端就是这样的报错：
![image](https://user-images.githubusercontent.com/64408436/80781284-64c8cc80-8ba4-11ea-8afb-b60eb31c6fd3.png)

纯小白一枚 希望大佬帮我看看如何解决，我的目标是外网访问我电脑上搭建的一个网页，这样做可以吗？我用的是你提供的Windows版本。谢谢大佬

**Comment by yzy613** [comment]
我先问一下，你的 IPv6 地址是程序自动获取的，还是手动查询的？
我刚刚排查了一下，“yzyweb.cn/ddns6” 服务挂掉了，我正在去修的路上，过会儿应该就可以使用了

**Comment by nbotu** [comment]
我又尝试在我的一台路由器使用，执行报错如下：
![image](https://user-images.githubusercontent.com/64408436/80781571-61821080-8ba5-11ea-993f-1a0ba1c496c5.png)

**Comment by nbotu** [comment]
> 我先问一下，你的 IPv6 地址是程序自动获取的，还是手动查询的？
> 我刚刚排查了一下，“yzyweb.cn/ddns6” 服务挂掉了，我正在去修的路上，过会儿应该就可以使用了

没想到大佬回复这这么快，我是自己填的。。我的网络有ipv6地址，难道不是自己填吗

**Comment by yzy613** [comment]
> > 我先问一下，你的IPv6地址是程序自动获取的，还是手动查询的？
> > 我刚刚排查了一下，“ yzyweb.cn/ddns6”服务挂掉了，我正在去修的路上，过会儿应该就可以使用了
> 
> 没想到大佬回复这这么快，我是自己填的。。我的网络有ipv6地址，难道不是自己填吗

应该是我的服务挂掉了（操作系统重做了），我这个程序设计的是自动获取 IP，我马上去修[笑哭]

**Comment by nbotu** [comment]
> > > 我先问一下，你的IPv6地址是程序自动获取的，还是手动查询的？
> > > 我刚刚排查了一下，“ yzyweb.cn/ddns6”服务挂掉了，我正在去修的路上，过会儿应该就可以使用了
> > 
> > 
> > 没想到大佬回复这这么快，我是自己填的。。我的网络有ipv6地址，难道不是自己填吗
> 
> 应该是我的服务挂掉了（操作系统重做了），我这个程序设计的是自动获取 IP，我马上去修[笑哭]

好的，谢谢大佬 那你看下我刚说的路由器运行报错是啥原因，好像是你的代码问题？

**Comment by yzy613** [comment]
> 我又尝试在我的一台路由器使用，执行报错如下：
> ![image](https://user-images.githubusercontent.com/64408436/80781571-61821080-8ba5-11ea-993f-1a0ba1c496c5.png)

你路由器是基于什么架构的？我现在支持了 amd64 arm64，如果不是，你就告诉我你的路由器架构是什么，我去发布一下

**Comment by yzy613** [comment]
你的 IPv6 地址是静态的还是动态的？

**Comment by yzy613** [comment]
解决了，你可以再试一试
