### ISSUE TITLE
IPv6 临时地址问题

### ISSUE THREAD

**Issue by NULL-LC** [yzy613/ddns#5]
# IPv6 默认是会分配临时地址的
- 临时地址生存时间非常短暂
- 只有用户的设备自身才能获取到默认的 IPv6 地址
- 对外连接操作系统会默认使用临时地址，故其他设备只能获取到临时地址
- 部分用户/运营商/路由器/交换机/操作系统可能会禁用临时地址

**Comment by yzy613** [comment]
# fixed it!
